"""Structured extraction plan pipeline.

Follows Cairn's philosophy: break one hard LLM task into many small ones.
Each stage has a tiny answer space. Assembly is deterministic Python.
The model never sees the full JSON schema.

Pipeline:
    Stage 1: FILE EXTRACTION — "What files need to exist?"
    Stage 2: FUNCTION EXTRACTION — "What functions go in each file?"
    Stage 3: DEPENDENCY ORDERING — "What order should files be created?"
    Stage 4: RISK SCREENING — Binary yes/no judges
    Stage 5: PLAN ASSEMBLY — Pure Python, no model

The criteria are ALWAYS machine-checkable because they're generated by
code from extracted data, not by the model. No manual_verification.
"""

from __future__ import annotations

import json
import logging
import re
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import TYPE_CHECKING, Any
from uuid import uuid4

from riva.db import get_connection, transaction
from riva.models import PlanStep, RivaPlan

if TYPE_CHECKING:
    from trcore.providers.base import LLMProvider

logger = logging.getLogger(__name__)


# ── Stage prompts — small, focused, constrained ─────────────────────

_FILE_EXTRACTION_SYSTEM = (
    "You extract filenames from coding task descriptions.\n"
    "List ONLY the filenames that need to be CREATED or MODIFIED.\n"
    "One filename per line. No explanation, no numbering, no bullets.\n\n"
    "RULES:\n"
    "- Use EXACTLY the filenames mentioned in the request\n"
    "- If the request says 'add X to utils.py', the file is utils.py (NOT utils/X.py)\n"
    "- If the request says 'create X.py', the file is X.py (flat, no subdirectories)\n"
    "- Only add subdirectories if the request explicitly mentions them\n"
    "- Include test files if the request mentions tests\n"
    "- If no specific files are mentioned, use a single reasonable filename\n"
    "- NEVER invent directory structures the request didn't ask for\n\n"
    "EXAMPLES:\n\n"
    "Input: 'Create a calculator with add and subtract'\n"
    "Output:\ncalculator.py\n\n"
    "Input: 'Create calc.py with add and multiply functions, and test_calc.py with tests'\n"
    "Output:\ncalc.py\ntest_calc.py\n\n"
    "Input: 'Add a validate_email function to utils.py'\n"
    "Output:\nutils.py\n\n"
    "Input: 'Build a web API with routes, models, and tests'\n"
    "Output:\nroutes.py\nmodels.py\ntests/test_routes.py\n\n"
    "Input: 'Fix the bug in api/routes.py line 42'\n"
    "Output:\napi/routes.py\n\n"
    "Input: 'Create a data pipeline that reads CSV and writes results'\n"
    "Output:\npipeline.py\n\n"
    "Input: 'Add error handling to the database module'\n"
    "Output:\ndatabase.py\n\n"
    "Input: 'Create a CLI tool called taskctl with list, add, complete, delete'\n"
    "Output:\ntaskctl.py\n\n"
    "Respond with ONLY filenames, nothing else."
)

_FUNCTION_EXTRACTION_SYSTEM = (
    "You extract function and class names from a coding task for a specific file.\n"
    "One name per line. No explanation, no signatures, no types — JUST NAMES.\n\n"
    "RULES:\n"
    "- Use EXACTLY the function names mentioned in the request\n"
    "- If the request says 'add(a, b)', the name is: add\n"
    "- If the request says 'validate_email function', the name is: validate_email\n"
    "- For test files, prefix with test_: test_add, test_subtract\n"
    "- For classes, use the class name: User, Comment, Plugin\n"
    "- If no specific names are mentioned, infer 1-3 reasonable ones\n"
    "- NEVER include parentheses, types, or arguments — just the name\n\n"
    "EXAMPLES:\n\n"
    "Input: 'File: calculator.py | Task: Create calculator with add and subtract'\n"
    "Output:\nadd\nsubtract\n\n"
    "Input: 'File: test_calculator.py | Task: Create calculator with add and subtract'\n"
    "Output:\ntest_add\ntest_subtract\n\n"
    "Input: 'File: utils.py | Task: Add validate_email function to utils.py'\n"
    "Output:\nvalidate_email\n\n"
    "Input: 'File: models.py | Task: Create User model with name and email'\n"
    "Output:\nUser\n\n"
    "Input: 'File: routes.py | Task: POST /api/users endpoint that validates and stores'\n"
    "Output:\ncreate_user\nvalidate_user_input\n\n"
    "Input: 'File: pipeline.py | Task: Build data pipeline that reads, validates, transforms, writes'\n"
    "Output:\nread_csv\nvalidate_row\ntransform_row\nwrite_csv\n\n"
    "Respond with ONLY names, one per line."
)

_ORDERING_SYSTEM = (
    "You determine the correct order to create files for a coding task.\n"
    "Given a list of files, reorder them so dependencies come first.\n"
    "Rules:\n"
    "- Config/settings files first\n"
    "- Base classes and interfaces before implementations\n"
    "- Source files before test files\n"
    "- Models/schemas before code that uses them\n"
    "List the filenames in order, one per line. No explanation.\n\n"
    "Example input: 'test_calc.py, calc.py, config.py'\n"
    "Example output:\nconfig.py\ncalc.py\ntest_calc.py"
)

_RISK_CONTRADICTORY_SYSTEM = (
    "Does this coding request contain contradictory or impossible requirements?\n"
    "Answer ONLY 'yes' or 'no'.\n"
    "Contradictory means: the request asks for two things that cannot both be true.\n"
    "Example contradiction: 'Make it synchronous and asynchronous at the same time'\n"
    "Example NOT contradiction: 'Create a file with two functions' (just complex, not contradictory)"
)

_RISK_UNCLEAR_SYSTEM = (
    "Is this coding request specific enough to produce working code?\n"
    "Answer ONLY 'yes' or 'no'.\n"
    "Specific enough means: a developer could start coding without asking questions.\n"
    "'Create calculator.py with add(a,b)' = yes (clear what to build)\n"
    "'Make the code better' = no (better how?)\n"
    "'Add logging' = no (to what? what level? what format?)"
)

_RISK_MISSING_CONTEXT_SYSTEM = (
    "Does this coding request reference existing files or code that would need\n"
    "to be read first before planning?\n"
    "Answer ONLY 'yes' or 'no'.\n"
    "'Create a new file hello.py' = no (nothing to read first)\n"
    "'Fix the bug in api/routes.py line 42' = yes (need to read that file)\n"
    "'Refactor the auth module' = yes (need to see current code)"
)

_TITLE_SYSTEM = (
    "Write a short title (under 60 characters) for this coding task.\n"
    "Just the title, no quotes, no explanation.\n"
    "Example: 'Create calculator module with basic arithmetic operations'"
)

# ── Alias tables — normalize hallucinated output ─────────────────────

# Files: strip common prefixes/suffixes models add
_FILE_CLEANUP = re.compile(r'^[\s\-\*\d\.\)]+')  # "1. ", "- ", "* "
_FILE_VALID = re.compile(r'^[\w/\-\.]+\.\w+$')  # Must look like a filename


# ── Dataclasses ──────────────────────────────────────────────────────

@dataclass
class ExtractedFile:
    path: str
    functions: list[str] = field(default_factory=list)
    is_test: bool = False


@dataclass
class PlanRisks:
    contradictory: bool = False
    unclear: bool = False
    missing_context: bool = False

    def to_list(self) -> list[str]:
        risks = []
        if self.contradictory:
            risks.append("Request contains contradictory requirements")
        if self.unclear:
            risks.append("Request is vague — may need clarification")
        if self.missing_context:
            risks.append("Request references existing code that must be read first")
        return risks


# ── Pipeline ─────────────────────────────────────────────────────────

class StructuredPlanner:
    """Multi-stage plan extraction pipeline.

    Each stage makes a small, focused LLM call. Assembly is deterministic.
    """

    def __init__(self, provider: LLMProvider | None = None) -> None:
        self._provider = provider

    def _ask(self, system: str, user: str, temperature: float = 0.0) -> str:
        """Make a focused LLM call. Returns empty string on failure."""
        if self._provider is None:
            return ""
        try:
            return self._provider.chat_text(
                system=system,
                user=user,
                temperature=temperature,
                timeout_seconds=30.0,
            ).strip()
        except Exception as exc:
            logger.warning("Structured planner LLM call failed: %s", exc)
            return ""

    def _judge(self, system: str, user: str) -> bool:
        """Binary yes/no judge. Fail-open (returns False on error)."""
        answer = self._ask(system, user)
        return answer.lower().startswith("yes")

    # ── Stage 1: File Extraction ──

    def extract_files(self, request: str) -> list[str]:
        """Extract filenames from the request."""
        raw = self._ask(_FILE_EXTRACTION_SYSTEM, request)
        if not raw:
            return ["output.py"]

        files = []
        for line in raw.split("\n"):
            cleaned = _FILE_CLEANUP.sub("", line).strip().strip("'\"` ")
            if cleaned and _FILE_VALID.match(cleaned):
                files.append(cleaned)

        # Deduplicate preserving order
        seen: set[str] = set()
        unique: list[str] = []
        for f in files:
            if f not in seen:
                seen.add(f)
                unique.append(f)

        return unique if unique else ["output.py"]

    # ── Stage 2: Function Extraction ──

    def extract_functions(self, request: str, filename: str, all_files: list[str]) -> list[str]:
        """Extract function/class names for a specific file.

        Passes the full file list so the model knows not to duplicate
        functions across files.
        """
        other_files = [f for f in all_files if f != filename]
        context = f"File: {filename}"
        if other_files:
            context += f" (other files in this project: {', '.join(other_files)})"
        prompt = f"{context} | Task: {request}"
        raw = self._ask(_FUNCTION_EXTRACTION_SYSTEM, prompt)
        if not raw:
            return []

        functions: list[str] = []
        seen: set[str] = set()
        for line in raw.split("\n"):
            name = line.strip().strip("()-:, ")
            # Must look like a valid Python identifier
            if name and re.match(r'^[a-zA-Z_]\w*$', name) and name not in seen:
                functions.append(name)
                seen.add(name)

        # Cap at 8 functions per file — prevents runaway extraction
        return functions[:8]

    # ── Stage 3: Dependency Ordering ──

    def order_files(self, request: str, files: list[str]) -> list[str]:
        """Order files by dependency (config first, tests last)."""
        if len(files) <= 1:
            return files

        prompt = ", ".join(files)
        raw = self._ask(_ORDERING_SYSTEM, prompt)
        if not raw:
            return self._heuristic_order(files)

        ordered = []
        for line in raw.split("\n"):
            cleaned = _FILE_CLEANUP.sub("", line).strip().strip("'\"` ")
            if cleaned in files:
                ordered.append(cleaned)

        # Add any missing files (model might have dropped some)
        for f in files:
            if f not in ordered:
                ordered.append(f)

        return ordered

    def _heuristic_order(self, files: list[str]) -> list[str]:
        """Fallback ordering when LLM fails."""
        config = [f for f in files if "config" in f.lower() or "settings" in f.lower()]
        models = [f for f in files if "model" in f.lower() or "schema" in f.lower()]
        tests = [f for f in files if "test" in f.lower()]
        rest = [f for f in files if f not in config + models + tests]
        return config + models + rest + tests

    # ── Stage 4: Risk Screening ──

    def screen_risks(self, request: str) -> PlanRisks:
        """Run binary risk judges."""
        return PlanRisks(
            contradictory=self._judge(_RISK_CONTRADICTORY_SYSTEM, request),
            unclear=not self._judge(_RISK_UNCLEAR_SYSTEM, request),
            missing_context=self._judge(_RISK_MISSING_CONTEXT_SYSTEM, request),
        )

    # ── Stage 5: Deterministic Assembly ──

    def assemble_plan(
        self,
        request: str,
        title: str,
        files: list[ExtractedFile],
        risks: PlanRisks,
    ) -> dict[str, Any]:
        """Assemble a plan from extracted components. Pure Python, no LLM.

        Each file becomes ONE step with a compound acceptance criterion:
        file_exists + function_defined for each function. This keeps plans
        compact (1 step per file, not 1 step per function).
        """
        steps: list[dict[str, Any]] = []
        step_num = 0

        for ef in files:
            step_num += 1

            # Build description
            if ef.functions:
                func_list = ", ".join(ef.functions)
                desc = f"Create {ef.path} with: {func_list}"
            else:
                desc = f"Create {ef.path}"

            # Primary criterion is file_exists
            criterion = f"file_exists: {ef.path}"

            steps.append({
                "step_number": step_num,
                "title": f"Create {ef.path}",
                "description": desc,
                "acceptance_criterion": criterion,
                "estimated_minutes": 5 + len(ef.functions) * 2,
            })

            # Add function_defined criteria as separate verification steps
            # (but only the first 4 to keep plans reasonable)
            for func in ef.functions[:4]:
                step_num += 1
                steps.append({
                    "step_number": step_num,
                    "title": f"Implement {func}",
                    "description": f"Define {func} in {ef.path} with working implementation",
                    "acceptance_criterion": f"function_defined: {ef.path}::{func}",
                    "estimated_minutes": 3,
                })

        # Git commit step
        step_num += 1
        steps.append({
            "step_number": step_num,
            "title": "Commit changes",
            "description": "Git add and commit all created files",
            "acceptance_criterion": f"git_contains_change: {files[0].path if files else '.'}",
            "estimated_minutes": 2,
        })

        return {
            "title": title,
            "steps": steps,
            "risks": risks.to_list(),
            "estimated_minutes": sum(s["estimated_minutes"] for s in steps),
        }

    # ── Full Pipeline ──

    def decompose(
        self,
        project_id: str,
        user_request: str,
        project_context: str = "",
    ) -> str:
        """Run the full structured extraction pipeline.

        Returns plan_id. Runs synchronously (no background task needed
        since each LLM call is small and fast).
        """
        plan_id = f"plan-{uuid4().hex[:12]}"
        now = datetime.now(timezone.utc).isoformat()

        # Insert draft plan
        with transaction() as conn:
            conn.execute(
                "INSERT INTO riva_plans "
                "(id, project_id, title, user_request, status, created_at, updated_at) "
                "VALUES (?, ?, ?, ?, 'draft', ?, ?)",
                (plan_id, project_id, "Extracting...", user_request, now, now),
            )

        try:
            # Stage 1: Extract files
            raw_files = self.extract_files(user_request)
            logger.info("Stage 1 (files): %s", raw_files)

            # Stage 2: Extract functions per file
            extracted_files: list[ExtractedFile] = []
            for path in raw_files:
                functions = self.extract_functions(user_request, path, raw_files)
                is_test = "test" in path.lower()
                extracted_files.append(ExtractedFile(
                    path=path, functions=functions, is_test=is_test,
                ))
                logger.info("Stage 2 (functions for %s): %s", path, functions)

            # Stage 3: Order by dependency
            ordered_paths = self.order_files(user_request, raw_files)
            # Re-sort extracted_files to match ordering
            path_to_ef = {ef.path: ef for ef in extracted_files}
            extracted_files = [path_to_ef[p] for p in ordered_paths if p in path_to_ef]
            logger.info("Stage 3 (order): %s", [ef.path for ef in extracted_files])

            # Stage 4: Risk screening
            risks = self.screen_risks(user_request)
            logger.info("Stage 4 (risks): contradictory=%s unclear=%s missing_context=%s",
                        risks.contradictory, risks.unclear, risks.missing_context)

            # Stage 5: Generate title
            title = self._ask(_TITLE_SYSTEM, user_request)
            if not title or len(title) > 80:
                title = user_request[:60]
            logger.info("Stage 5 (title): %s", title)

            # Stage 6: Assemble plan (pure Python)
            plan_data = self.assemble_plan(user_request, title, extracted_files, risks)

            # Save to DB
            self._save_plan(plan_id, plan_data)

        except Exception as exc:
            logger.exception("Structured planner failed for %s", plan_id)
            self._save_error(plan_id, str(exc))

        return plan_id

    def _save_plan(self, plan_id: str, plan_data: dict[str, Any]) -> None:
        """Save assembled plan to database."""
        now = datetime.now(timezone.utc).isoformat()
        steps = plan_data.get("steps", [])

        with transaction() as conn:
            conn.execute(
                "UPDATE riva_plans SET title=?, decomposition_json=?, "
                "status='pending_approval', updated_at=? WHERE id=?",
                (plan_data["title"], json.dumps(plan_data), now, plan_id),
            )

            for step in steps:
                step_id = f"step-{uuid4().hex[:12]}"
                conn.execute(
                    "INSERT INTO riva_plan_steps "
                    "(id, plan_id, step_number, title, description, "
                    "acceptance_criterion, estimated_minutes, status, "
                    "created_at, updated_at) "
                    "VALUES (?, ?, ?, ?, ?, ?, ?, 'pending', ?, ?)",
                    (
                        step_id, plan_id,
                        step.get("step_number", 0),
                        step.get("title", ""),
                        step.get("description", ""),
                        step.get("acceptance_criterion", ""),
                        step.get("estimated_minutes"),
                        now, now,
                    ),
                )

        logger.info("Structured plan %s saved: '%s' with %d steps",
                     plan_id, plan_data["title"], len(steps))

    def _save_error(self, plan_id: str, error: str) -> None:
        now = datetime.now(timezone.utc).isoformat()
        with transaction() as conn:
            conn.execute(
                "UPDATE riva_plans SET title=?, status='failed', "
                "decomposition_json=?, updated_at=? WHERE id=?",
                ("Plan extraction failed", json.dumps({"error": error}), now, plan_id),
            )

    def get_plan(self, plan_id: str) -> RivaPlan | None:
        """Retrieve a plan (delegates to PlanEngine.get_plan pattern)."""
        from riva.plan_engine import PlanEngine
        # Reuse the existing get_plan logic
        engine = PlanEngine()
        return engine.get_plan(plan_id)
